### ISSUE TITLE
Undelivered input from ephemeral wire

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1159]
This is a fun one. I can't decide whether this is a bug or not. /cc @dglazkov 

1. Make a blank board
2. Rename `output-2.text` to `output-2.text-foo`.
3. Move the (now ephemeral) edge to `output-2.text-foo`.
4. Rename `input-1.text` to `input-1.text-bar`.
5. Run the board.

Because the edge is still expressed as:

```json
"edges": [
  {
    "from": "input-1",
    "to": "output-2",
    "out": "text",
    "in": "text-foo"
  }
]
```

The `text` input is picked up but no longer delivered.

Board attached: [board.json](https://github.com/breadboard-ai/breadboard/files/14694648/board.json)

**Comment by paullewis** [comment]
![nodes](https://github.com/breadboard-ai/breadboard/assets/617438/a259b202-a6f6-4611-8221-0fd2f0814709)

This is how the nodes appear in the Visual Editor. The implication seems to be that `text` should come through to `text-foo`. Feels related to #930.

**Comment by dglazkov** [comment]
yeah, something's weird here.

**Comment by dglazkov** [comment]
oh I know. `input` describer doesn't pick up the ephemeral edge. When running, it only asks for `text-foo`, and not the `text`. And so it can't move across the `input-1.text -> output-2.text-foo` edge.

One bug and one feature request in here:

1. Make `input` describer recognize ephemeral edges

2. Better UI for when the graph stops because it's miswired.
