### ISSUE TITLE
Visual Editor MVP ☂️

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1309]
Let's make Visual Editor minimally sufficient for building useful graphs. The umbrella bug.

- [x] #1315
- [x] #1321
- [x] Add/edit ad hoc wires (necessary for `runJavascript`, though there might be other strategies here (related #1255)
- [x] #1394
- [ ] "Make a copy" of an existing graph (#1143)
- [x] Being able to set behavior and format on fields. (can't have "multiline" inputs or "markdown" outputs without that, here's an [example](https://github.com/dglazkov/song-writer-team/commit/077a279fa3e8b13adeaf08424eb3718d07a43d1e) of me editing JSON directly to get it there)
- [x] #1317
- [x] #1372
- [x] Handle control wires in Visual Editor (a "maybe" for MVP)

**Comment by dglazkov** [comment]
Started adding the necessary APIs for inspectability/editability of subgraphs in #1314.

**Comment by paullewis** [comment]
Per our offline conversation, I think for subgraph / embed views we need:

1. A playground subgraph example where it's like "this already has a graph inside that you should be able to open and inspect".
2. A way for someone to add a "placeholder subgraph" and add to it. So let's say that I start with `blank.json` and I want to add an embedded subgraph... how do I do that? Do we want to add something to the built-in kit?

I think there may be some work here around the Editor API because IIRC we currently only emit the ID of the node and its configuration, but I suspect we need to say something more about _which_ subgraph we're talking about unless all nodes, embedded or otherwise, have distinct IDs?

**Comment by dglazkov** [comment]
> A way for someone to add a "placeholder subgraph" and add to it. So let's say that I start with `blank.json` and I want to add an embedded subgraph... how do I do that? Do we want to add something to the built-in kit?

Here's a nascent editor API for this: https://breadboard-ai.github.io/breadboard/docs/editor/#editing-subgraphs

**Comment by paullewis** [comment]
What I'm wondering is whether this needs to appear like a node... becauuuuuuse when it comes to laying out the graph we presumably want something rendered there that's like "hey we have a subgraph here" and that feels like an atomic unit in the same way that input and output are, and we'd want to render it with ports and so on.

But then it has this special ability for us to dive inside and edit. Which I suspect is mostly a case of querying the subgraph info and acting accordingly in the UI.

**Comment by dglazkov** [comment]
Control wire support landed in  #1377

**Comment by dglazkov** [comment]
Declaring victory 🚢
