### ISSUE TITLE
[breadboard-web] schemish node's `schema` value only lets you select a board

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1418]
I'm trying to build a graph with a `schemish` node from `json-kit`. The UI doesn't let me drop in a JSON schema and instead asks me to provide a board. I need to add JSON in directly but can't

<img width="761" alt="Screenshot 2024-04-15 at 10 52 12" src="https://github.com/breadboard-ai/breadboard/assets/45510/0bc084d0-9fce-4146-8c64-3b0e2cca9666">

It looks like if the input is expecting an `object` it uses the board picker.

**Comment by paullewis** [comment]
Yeah, if the type is `object` and the `behavior` is set to `board` that's right, it will. I'll take a look.

**Comment by paullewis** [comment]
Okay, so I think I need a consult from @dglazkov here, because we switch over to the board selector when this evaluates to `true`: https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard-ui/src/utils/board.ts#L13-L25. However, looking over the code I'm not clear why we return certain values (like `if (!value) return true`), so it's likely I'm missing some context.

In other words, though, @PaulKinlan, I suspect this _is_ a bug and that we are too keen to provide the board selector, I'm just not familiar with this particular function. I can work around it in the short term by switching a couple of cases around which I think will help. I'll do that now.

**Comment by dglazkov** [comment]
Yup, was a bug 🐛

**Comment by paullewis** [comment]
We no longer have a `schemish` board so closing this.
