### ISSUE TITLE
Improve `llm-content` editor for Visual Editor Easy Mode

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1471]
Currently, our `llm-content` editor looks like this:

<img width="1004" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/1934/01ed2450-6a4f-455c-a312-81b303bcc496">

It's good, but probably not super-friendly for immersive prompt editing. Let's figure out what it needs to look like for the Visual Editor Easy Mode MVP.

**Comment by paullewis** [comment]
Something in this area that's worth exploring. At some level `llm-content` is really generic, inasmuch as it's some base64-encoded data with a mime type, whether that be for images, text, or audio files. In the same vein we also have drawables, webcam access, and microphone access, which are more direct for the user than a file, but which we still emit in the same format: base64-encoded data with a mime type.

So I wonder, is there a version of this UI where we support not just files, but also device access too? From an API perspective there's little to stop me mixing webcam with some audio and a text file because they can all come through as base64 + mime. What we can then do from a UI perspective is allow someone to go from that "anything goes" version of events to a more limited palette by specifying – say – filters: `allowed=['webcam', 'microphone', 'image']`.

wdyt?

**Comment by dglazkov** [comment]
Some notes on https://breadboard-ai.web.app/?board=%2Fgraphs%2Fsuper-worker-test.json so far:

There seems to be four UI surfaces for the `llm-content` that I can see:

1. The configuration editor in Selected Node panel:
<img width="532" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/1934/7b2207bd-5cb8-48df-ac09-ba9cb42d8a25">

2. The unsubmitted input the Board panel during a run:
<img width="497" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/1934/ef5065ef-303e-450f-b088-0097f2b8107e">

3. The submitted input in the Board panel during a run:
<img width="500" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/1934/05aad38b-6dfa-4303-9e06-511aac34e9e7">

4. The output in the Board panel during/after a run:
<img width="501" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/1934/ea1c6287-42df-424e-83ff-dc7b52b7ded5">

My intuition is that 1 and 2 should look/act roughly the same. And 3 and 4 should be similarly paired. The 4 is a little weird, because it's actually an array of `llm-content`. Maybe for MVP we just show the last element?

In more general, frameworkey terms, it looks like maybe there's an Input/Output provider for a given behavior, and it maybe vends a web component with a pre-defined properties/events?

WDYT?

**Comment by dglazkov** [comment]
Found one more place where the the "llm-content" editor could go: in the schema editor. Very turducken.

![image](https://github.com/breadboard-ai/breadboard/assets/1934/9a42cd21-ecf0-4212-ad41-10f56366abb0)

**Comment by paullewis** [comment]
I think anywhere with the `behavior` of `'llm-content'` should get either the editor or the renderer, depending on the context, right?

**Comment by paullewis** [comment]
I think we can probably declare victory here!

**Comment by paullewis** [comment]
I have [a follow-up bug for the Activity Log](https://github.com/breadboard-ai/breadboard/issues/1583) so I'm going to close this one :shipit:
