### ISSUE TITLE
Possibly remove LLMContent assertions?

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#1717]
On the heels of https://github.com/breadboard-ai/breadboard/pull/1716,

Let's consider removing the LLMContent assertions altogether in 
https://github.com/breadboard-ai/breadboard/blob/fix-llm-content/packages/breadboard-ui/src/utils/schema.ts,

now that we have a nice text editor.

**Comment by paullewis** [comment]
Closing because we need these assertions to check that data from a previous run is still valid when launching a new run. Say, for example, we have an `object` that is `behavior[board]` and we do a run, then switch it to, `behaviour[LLM Content]` and run it again. We check with the assertions that what we are about to pass through is an LLM Content.
