### ISSUE TITLE
Missing output `end` property

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1777]
I'm seeing cases on `main` (graphs/super-worker-test.json) where the final `output` node doesn't seem to have an `end` value, which means that when we get to https://github.com/breadboard-ai/breadboard/blob/main/packages/breadboard-ui/src/elements/activity-log/activity-log.ts#L332 we go into the "pending" UI rather than the "finished" one. 

What's odd about this is if I log out the event and check in DevTools I see it has an end value. If I log the end property directly it's set to `null`. Makes me wonder if there's a race condition and the value is being set slightly after the event is being emitted? Not sure if that's possible, though...

I don't _think_ this is related to my changes today, but it's a bit tricky to debug.

**Comment by dglazkov** [comment]
The culprit appears to be in the introduction of the guard for activity log. The guard was using the `eventPosition`:

https://github.com/breadboard-ai/breadboard/commit/e80f055b8089fb87f60f400793696b77a1876a09#diff-c82519e05c956c4851e65d492160ee1bd77cdb38977e5f299a1a08f7c8983448R385

However, `eventPosition` will not change for `nodeend`, since that event will only "close out" the existing node, rather than adding a new one.

The fix I landed guards against `this.run?.events`, which changes (or at least should change) the identity whenever there's an interesting thing that happens to the events lits.

**Comment by paullewis** [comment]
Ah, my mistake. Thanks for finding the fix!

**Comment by paullewis** [comment]
Yeah we needed the guard to allow a re-render of the details panel while avoiding a re-render of the activity log.
