### ISSUE TITLE
[FR] Editor API support for multi-change

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#1834]
Now we can deal with multiple nodes & edges at once, it would be good if I could send all the visual changes at once to the Editor API. I'm thinking here of things like moving all the nodes at once, which I think would only work if I can update multiple nodes values in lockstep.

Might also be handy for other operations, too, where we don't necessarily want n changes to be emitted, but rather treating the changes as a single transaction of sorts.

@dglazkov wdyt?

**Comment by dglazkov** [comment]
Love it, obvs.

**Comment by dglazkov** [comment]
This makes me wonder if we're due for Editor API redesign. Instead of multiple `canDo` and `do` methods, maybe it's really just two methods: `canChange` and `change`, both taking a list of changes, and acting as one atomic edit -- one version increment. This would also be nicer for undo/redo, obvs.

Let me start with adding these two methods and see if we can add multitudeness to it.

**Comment by dglazkov** [comment]
An interesting thing about multi-edits -- they need to have a way of rolling back, so I will need to create a copy of a graph descriptor, apply changes to it, and then, if successful, copy it over.

**Comment by paullewis** [comment]
> This makes me wonder if we're due for Editor API redesign. Instead of multiple `canDo` and `do` methods, maybe it's really just two methods: `canChange` and `change`, both taking a list of changes, and acting as one atomic edit -- one version increment. This would also be nicer for undo/redo, obvs.
> 
> Let me start with adding these two methods and see if we can add multitudeness to it.

This sounds exactly right to me. Then a current change is just a single list item.
