### ISSUE TITLE
[Bug] Undo doesn't update Property Panel

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#1873]
When I use Command Z to undo an edit in the graph, I see the change immediately. When I undo a chance in the Node property panel, the change is not visible but if I click off the panel and back on the node, I see the change. I think the panel needs to be updated on Undo.

(Unmute for audio description in the video)

[Bug Undo in Activity Panel.webm](https://github.com/breadboard-ai/breadboard/assets/123408/fcceda8a-1252-4730-a243-453effde3a83)

**Comment by paullewis** [comment]
Yeah, this one is particularly tricky because we would _usually_ use the fact that the graph has changed as an indicator to re-render. We can't do that here because when a user enters data it causes the graph to change, then the form re-renders and input focus is lost. So what I'm doing is using the graph to mark the change, but I'm also ignoring any graph change that occurs immediately after an input event in either the node metadata or node configuration elements.

Hopefully that's the right behavior, it certainly _seems_ to be, but there may be some other edge cases that emerge.
