### ISSUE TITLE
Can no longer pick graphs in invoke

### ISSUE THREAD

**Issue by PaulKinlan** [breadboard-ai/breadboard#1919]
<img width="623" alt="Screenshot 2024-05-22 at 20 14 57" src="https://github.com/breadboard-ai/breadboard/assets/45510/099cdb94-603a-482b-b1d4-c95740b2326a">

I would expect the "board" to be a drop down of existing boards that I've added.

Sample board: https://github.com/breadboard-ai/breadboard/blob/main/boards/tools/openapi/openapi-toolworker.json it links to aboard from the FS (which is a local copy of https://raw.githubusercontent.com/breadboard-ai/breadboard/main/boards/tools/openapi/openapi.json)

**Comment by dglazkov** [comment]
@aomarks would love your help here. The issue stems from 

https://github.com/breadboard-ai/breadboard/blob/8e2c44d5b1650cce21701ab5aaa6ca2d99ed3921/packages/core-kit/src/nodes/invoke.ts#L104

when marked as "unknown" type, the resulting JSON Schema type is an array of all possible types. This breaks the UI, since we expect the type to be "object":

https://github.com/breadboard-ai/breadboard/blob/8e2c44d5b1650cce21701ab5aaa6ca2d99ed3921/packages/breadboard-ui/src/elements/node-info/node-configuration.ts#L773-L805

I tried changing "unknown" to "object" in invoke.ts, but it starts to complain. What's the best way to address this?

**Comment by dglazkov** [comment]
Got it! 

```diff
-  type: "unknown", 
+ type: object({})
```

**Comment by aomarks** [comment]
(sorry, missed this thread earlier)

> Got it!
> 
> ```diff
> -  type: "unknown", 
> +  type: object({})
> ```


Cool! But can't it also be a string URL?

**Comment by aomarks** [comment]
> Got it!
> 
> ```diff
> -  type: "unknown", 
> +  type: object({})
> ```

Also, note that the 2nd argument to `object` determines whether the object is open or closed (i.e. the value of `additionalProperties` in JSON schema). With no 2nd argument, it is closed. Examples:

1. `object({})` creates:

```json
{
  "type": "object",
  "additionalProperties": false
}
```

2. `object({foo: "string"})` creates:

```json
{
  "type": "object",
  "properties": {
    "foo": {
      "type": "string"
    }
  },
  "additionalProperties": false
}
```

3. `object({}, "unknown")` creates:

```json
{
  "type": "object",
  "additionalProperties": true
}
```

4. `object({}, array("number"))` creates:

```json
{
  "type": "object",
  "additionalProperties": {
    "type": "array",
    "items": "number"
  }
}
```

So I think in your case you want #3 (any kind of object) instead of #1 (an empty object).

(I'm open to switching up this syntax a bit to make this more intuitive)
