### ISSUE TITLE
[UX] Can we make more graceful default states for nodes

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#2009]
I'm finding some things repetitive and likely potential challenges for new users to Breadboard. Sorry for the potpourri of issues but here's a list of small tweaks I keep running into:

1. When i create a new input node or an output node, we should populate a default port. 
<img width="464" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/1b6e2700-8ec5-4ef1-8a9e-3b935d0e1580">

2. Currently when you create a default port in the scheme for an input and output node, it defaults to string. I think this should default to Object > LLM_content (this one may be up for debate).

3. While I love the LLM_content element, I find the repetition of always having to clicking a text part before typing to be a small but constant roadblock. Especially when building a chatbot. Not having the focus in the user input text area slows things down substantially. As a solve could we autocreate a text part in the LLM_content when the user focus on that control assuming there are no parts in that editor.

4. If I pass a string to the Context in of a Specialist I get a weird error that doesn't explain the error about an input mismatch so it's hard to debug. Can we make this error more explanatory?
<img width="358" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/84cea6ba-fcf2-4da1-ac6d-b819b22c4734">

5. I believe the schema ID should go into the hidden options in the schema editor. The duplication of ID and Title always confuses me.
<img width="352" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/a4fd395b-8c65-4f22-ab7e-6ea17520f00b">

**Comment by paullewis** [comment]
Thoughts:

1. Agreed - I have a patch incoming for this.
2. Also agreed - let's try it at least.
3. This one I think is about the defaults. I am highly reticent to just create a new part when there are none, since that's what the port's default field is really for. What I've done in my incoming patch, though, is to not only set the input to have an LLM Content port, but I have also set its default value to be a single empty text part. That way when you go to it its defaults aren't empty. Hopefully that makes sense.
4. I think this is about the retry not capturing and emitting the underlying errors. I will file a bug for @dglazkov, because I think what we probably should do is emit the errors when we run out of retries.
5. Done.

**Comment by paullewis** [comment]
Another thing on 4 is that we shouldn't be letting you connect a string -> LLM Content. We do have some work to do there to prevent mismatching port types, which we have yet to finish, but that would also help. In any case, I've filed a bug for what we do when retries are exhausted.
