### ISSUE TITLE
[UX] The board actions should change with editable and non-editable boards

### ISSUE THREAD

**Issue by donsbach** [breadboard-ai/breadboard#2010]
Now that we have shared providers, users will be openning other people's boards often. Currently if I open someone elses board I can't tell it's not editable because it presents a Save button that doesn't do anything.

Instead we should have features for editable boards that look like this:
<img width="344" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/f52dce25-1733-4dc9-954f-c502afc5f816">

And features for uneditable boards that look like this:
<img width="364" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/123408/ab50cb80-fc36-4bef-b905-0436025a23c9">

**Comment by paullewis** [comment]
The short term "fix" I'm landing for this is to only show the Save button when a user has write access on the provider. We did have a check for this, but it wasn't matching paths and that meant it was showing the Save button when it shouldn't have.

The longer term play is as you say, @donsbach, to tidy up the UX so that there's an overflow menu and "Save a copy" etc.

**Comment by donsbach** [comment]
it's probably not just writable providers, but editable boards, right? i could open your board on a writable provider and wouldn't see save only export right?

**Comment by paullewis** [comment]
I think we have the machinery in place for this now (Save vs Save As... etc) so I'm going to declare victory. :shipit:
