### ISSUE TITLE
When `breadboard-web` grows up

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#206]
Currently, `breadboard-web` is home to many things. Let's try to imagine what all these things want to be when they grow up. I see these paths:

- **Debugger** - The debugger UI bits graduate to `breadboard-debugger` or to `breadboard-cli`. My preference is to have a separate debugger package mostly because I like cli tools to be shallow: contain lots of deps, but only glue code in themselves.
- **Gallery** - The various boards we've built in `src/boards` and their respective json/md comrades graduate to some sort of `breadboard-playground`, which is (waving hands) some sort of a place/site to showcase, discover, and share AI recipes.
- ~~**Harnesses** - The three harnesses (main-thread, worker, proxy-server) need to go somewhere, too. Maybe their own packages? Both debugger and gallery depend on these packages.~~ -- Harness bits were moved to `packages/breadboard`

Once that happens, `breadboard-web` disappears. WDYT?

@paullewis @PaulKinlan

**Comment by paullewis** [comment]
I think the debugger would make a standalone thing. I think we need a collection of boards, too, some of which are demos, some of which are more like "fancy components". So there's a showcase aspect, yep, but I think also a "maker store" aspect, too?

In terms of the harnesses, though, I'm a little less sure. I keep wondering if we can unify them somehow.

One more package is the shared UI between the app gen side and the debugger.

**Comment by dglazkov** [comment]
#164 would likely be take debugger as a dependency. Also, it's probably not called "debugger". More like a "code-first breadboard IDE"..?

**Comment by PaulKinlan** [comment]
re: Harnesses - some part of this feels pretty core to breadboard, I do wonder if they should be in `breadboard`. I could imagine `Worker` being used for isolation in a cli and on the web, Proxy/HTTP being used in the CLI too.... Although, I'm not to sure if they are too heavy weight. 

Either way, I would love them somewhere more useable.

Debugger/CLI - agree with the CLI being lightweight. One example, I copy the entire repo `breadboard-web` in to the `dist\ui` folder so that you can spin up the UI pretty easily. With just a couple of tweaks we could have `breadboard-web` as a published package and all the assets exported... that way the CLI are always in sync with the breadboard version.

**Comment by paullewis** [comment]
Yeah I wonder, would it be possible to have one harness with multiple modes?

**Comment by dglazkov** [comment]
> Yeah I wonder, would it be possible to have one harness with multiple modes?

Maybe like a configurable harness? Takes in the kits and some config?

**Comment by paullewis** [comment]
Right! One harness with different modes depending on your needs. Not sure if it's doable or not. I think both @PaulKinlan and I have both replicated the Worker one for our satellite projects, and, yeah I think having access to a single harness would be awesome.

**Comment by dglazkov** [comment]
Filed #233 for the gallery bit.

**Comment by dglazkov** [comment]
Filed #297 for the debugger (Lab!) bit.

**Comment by dglazkov** [comment]
Shall we rename `breadboard-web` to `debugger` or `lab` something?

**Comment by dglazkov** [comment]
Declaring victory 🚢
