### ISSUE TITLE
Input examples not displaying as expected in bb-web

### ISSUE THREAD

**Issue by TinaNikou** [breadboard-ai/breadboard#2490]
When examples are listed for an input, they are not clearly displayed, or able to be selected, in Breadboard-Web when running the board.
![Image](https://github.com/breadboard-ai/breadboard/assets/104843955/dc098415-d1e4-4b48-8e81-d4d27d9f1213)
It would be expected for the input examples to be shown to the user and even be selected, such as from a dropdown list, where the user can also enter a custom option, if necessary.

The examples can just be seen in the schema editor.
![Image](https://github.com/breadboard-ai/breadboard/assets/104843955/872fc807-d287-473c-a463-44e27b9e0c14)

Example board code:
```typescript
import { board, input, output } from "@breadboard-ai/build";
import { code } from "@google-labs/core-kit";

const examples = input({
    type: "string",
    title: "Input with Examples",
    examples: ["First", "Second", "Third"]
});

const passthrough = code(
    {
        examples
    },
    {
        examples: "string"
    },
    ({ examples }) => {
        return { examples }
    }
);

export default board({
    title: "Examples Example",
    inputs: { examples },
    outputs: {
        examples: output(passthrough.outputs.examples),
    }
});
```
Example board JSON:
```json
{
  "title": "Examples Example",
  "edges": [
    {
      "from": "input-0",
      "to": "runJavascript-0",
      "out": "examples",
      "in": "examples"
    },
    {
      "from": "runJavascript-0",
      "to": "output-0",
      "out": "examples",
      "in": "examples"
    }
  ],
  "nodes": [
    {
      "id": "input-0",
      "type": "input",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "examples": {
              "type": "string",
              "title": "Input with Examples",
              "examples": [
                "First",
                "Second",
                "Third"
              ]
            }
          },
          "required": [
            "examples"
          ]
        }
      }
    },
    {
      "id": "output-0",
      "type": "output",
      "configuration": {
        "schema": {
          "type": "object",
          "properties": {
            "examples": {
              "type": "string"
            }
          },
          "required": [
            "examples"
          ]
        }
      }
    },
    {
      "id": "runJavascript-0",
      "type": "runJavascript",
      "configuration": {
        "code": "const run = ({examples:examples2})=>{return{examples:examples2}};",
        "name": "run",
        "raw": true
      }
    }
  ]
}
```

**Comment by alexandraM98** [comment]
I had a quick look at this and checked the [input](https://github.com/breadboard-ai/breadboard/blob/main/packages/visual-editor/src/ui/elements/input/input.ts) component. I'll briefly share some of my findings/things I noticed:

- Assuming that we want an html `<select>` for displaying the `examples` property's options, currently a `<select>` seems to only be rendered if we set the `enum` property on the schema. 

- The [`isSelect`](https://github.com/breadboard-ai/breadboard/blob/4bf8894688045eba52f0b2087aeba988c60fe8e8/packages/visual-editor/src/ui/utils/index.ts#L17C1-L19C2) function checks whether a dropdown should be rendered and at the moment that is decided based on the following condition: `schema.enum && schema.enum.length > 0`. I just wanted to see if I can get the `examples` property as a dropdown and if I replace enum with examples in that condition, I get the desired output. 

- Basically, I think if we want to see a dropdown for displaying the entries of the `examples` array, we need to look at this [`if`](https://github.com/breadboard-ai/breadboard/blob/4bf8894688045eba52f0b2087aeba988c60fe8e8/packages/visual-editor/src/ui/elements/input/input.ts#L306C9-L436C12) statement or change the condition for [`isSelect`](https://github.com/breadboard-ai/breadboard/blob/4bf8894688045eba52f0b2087aeba988c60fe8e8/packages/visual-editor/src/ui/utils/index.ts#L17C1-L19C2).

- Also, as @TinaNikou also suggested, it might be nice to be able to add a free text option to dropdowns. For example, the way I'm imagining this is something like: at the bottom of a dropdown there could be an additional entry with the text `+ Add custom option` and allow users to add a new option directly from the dropdown instead of having to edit the schema.

**Comment by alexandraM98** [comment]
I tried to fix this in a new branch [here](https://github.com/ExaDev/breadboard/tree/make-input-examples-selectable-from-dropdown)

If there is an `examples` property on the schema, you will see a dropdown with the options. Same goes for the `enum` property and the example also works with both properties declared at once. Below you can see the resulting behaviour after adding the new conditions:

https://github.com/user-attachments/assets/dd0cd55c-0fd3-4f98-847b-7010ebc70a7e
