### ISSUE TITLE
Bring back the visual debug view

### ISSUE THREAD

**Issue by itsjorgebar** [breadboard-ai/breadboard#2705]
## Expected Behavior

Joiner components used to display visual debug output.
![image](https://github.com/user-attachments/assets/319cc203-0951-4a41-b727-ab79b19b3470)

## Actual Behavior
Now, the output is in JSON format.
![image](https://github.com/user-attachments/assets/3b2da55b-4cc4-425a-9ad3-57b52ae40932)

## Steps to Reproduce the Problem

1. Run a board that includes a Joiner, such as the [Novel Outliner.](https://breadboard-ai.github.io/breadboard/docs/guides/novel-generator/)

## Caveat

If the current behavior is intended, we can leave it as it is.

**Comment by dglazkov** [comment]
@paullewis is this because of the inputs refactor?

**Comment by paullewis** [comment]
It works if the joiner is set to merge the conversations because it effectively flattens its inputs down to an `LLMContent[]`, but without that checkbox ticked it fails the check at https://github.com/breadboard-ai/breadboard/blob/main/packages/visual-editor/src/ui/elements/activity-log/activity-log.ts#L494

Looking at a console output, I imagine it's because of the `$metadata`:

<img width="290" alt="Screenshot 2024-08-02 at 09 24 24" src="https://github.com/user-attachments/assets/839faf17-a767-46fe-921c-80277792a35c">

So there are probably a couple of options here:

1. Teach the LLM Content Array test to ignore `$metadata` and the viewer to ignore any such objects.
2. Keep everything as-is, but don't include the `$metadata` in the joiner's outputs.

I'm guessing option 1. is the better of the two, but I'm also not totally clear on what we use the `$metadata` for to call it either way.

**Comment by dglazkov** [comment]
Yeah, option 1 for now -- and expand it eventually to teach LLM Content Array to understand $metadata and display it properly.
