### ISSUE TITLE
Board remains in "Stop Board" state

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3277]
- Create a blank board
- Hit "🐞   Debug Board"
- Enter input and hit continue
- The board completes
- The button still says "Stop Board"

@paullewis

**Comment by paullewis** [comment]
Ah, it's because I'm gating the behavior on the existence of the TGO in the editor: https://github.com/breadboard-ai/breadboard/blob/main/packages/shared-ui/src/elements/editor/editor.ts#L1689-L1691

However, the currentNode no longer goes back to `null` when the run finishes. Would it be possible to have something on the TGO that indicates the run status? It feels like we're going to want something like this at some point anyway.

**Comment by dglazkov** [comment]
Yup, let me plumb this real quick.
