### ISSUE TITLE
The "Custom" tab in the Schema editor is destructive

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3386]
- Go to the [Librarian board](https://breadboard-ai.web.app/?tab0=https://breadboard-ai.web.app/example-boards/examples/librarian.bgl.json)
- Click on "Schema" of the input
- Click "Custom"

## Expected Behavior

The editor shows something like this:

```json
{
  "type": "array",
  "title": "Context",
  "examples": [],
  "items": {
    "type": "object",
    "behavior": ["llm-content"]
  },
  "default": "[{\"role\":\"user\",\"parts\":[{\"text\":\"\"}]}]",
  "description": "What book are you looking for?"
}
```

## Actual Behavior

The editor shows:

```json
{
  "type": "object",
  "title": "Context"
}
```

**Comment by dglazkov** [comment]
There's something here also about destructiveness of switching between tabs.

- When switching to "Custom", we don't change the schema, just reveal what was there.
- When switching to "Text", if the schema is text-like, then we just use it. Otherwise, we warn the user that the schema will be replaced with a generic text schema
- When switching to "Conversation Context" -- same as for "Text"

**Comment by paullewis** [comment]
Alright, going to go with the change in #3392, but let's reopen this if it's not better. What we do now is:

1. Try and infer the view from the property. If it fits `LLMContent[]` or text (`type="string"`) and only a few set of known properties) then we set the view to the known type.
2. If the property does not fit, or it has extraneous properties, show the custom view.
3. The user can change to the custom view at any time and it is non-destructive.

The only "quirk" (maybe feature?) is that if you switch – say – `LLMContent[]` to custom, make no changes, close & reload you will get the `LLMContent[]` view because of the type inference in 1. above.
