### ISSUE TITLE
The board server is slow to show up in provider drop-down

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#3388]
In both the side panel and the "Save As.. " provider menu, the board server can be slow to show up, making it look like VE forgot about it. 

This happens when the board server instance takes a few seconds to warm up, so there's a weird twilight zone in the UI until it is fully ready.

This is something that's been a common problem during the hackathons: peeps were confused not seeing the server.

Not exactly sure what to do here. Maybe just make it pop up in the drop-downs, and handle the fact that it isn't yet ready through some other means?

@paullewis would love your thoughts here.

**Comment by paullewis** [comment]
A fun puzzle.

We were mostly there with this one inasmuch as the nav doesn't hang around for the board server instance to populate, buuuuut it also wasn't creating a "placeholder" store for it. This in turn meant that the store list for the remote graph provider would appear empty in most cases, at least until the board server instance has booted and the store got created and populated at the same time.

So the fix boils down to creating an empty store for the board server up front so that it shows in the nav, and then awaiting its contents as we currently do. That way it always shows up in the list and if you select it before its contents have loaded you will see the "Loading..." message.
