### ISSUE TITLE
Prepare harness for board replay capabilities

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#342]
Let's teach the harness to replay board runs! To do that:

- [x] Expose `state` on the `nodestart` and `nodeend` events.
- [x] Add API to resume board run from a saved state
- [x] Make `state` an array of objects
- [ ] Deprecate `path`
- [ ] Teach runner to resume at the beginning of the node, not the end of it
- [ ] Teach runner to resume for sub-graphs (this is #136)

**Comment by dglazkov** [comment]
@paullewis @seefeldb I am thinking about unifying `path` and `state`. Once unified, here's how it will work:

- `path` goes away
- `state` becomes an array of objects
- each object (let's call it `RunStackItem`) in the array represents the invocation and the current state within a given graph
- just like `path`, the array grows and shrinks, effectively becoming the "invocation stack" of a run
- new entry is added on every `graphstart` and removed on every `graphend`.

The `RunStackItem` has these properties:
```ts
type RunStackItem = {
  graphInvocationId: number; // commonly zero, but will increment for cases like `map`.
  nodeInvocationId: number // same as the number in `path`
  state: TraversalResult
}
```

Combined with data in `graphstart`, this should give us enough information to reconstruct a run and restart a graph from any point, even from multiple nested subgraphs.

WDYT?

**Comment by paullewis** [comment]
I can see us having to merge sub-state objects into one global state if we want to do something like a resume. Or, equivalently, parsing a global state into multiple sub-states so that we can boot each sub graph in the right way. So there's additional bookkeeping there, I think (unless I've misunderstood the idea!).

I'm assuming that path is a bit brittle, and that the hope is we can have something a little more robust. Is that the thinking behind this?

**Comment by dglazkov** [comment]
yep, that's the idea!

**Comment by dglazkov** [comment]
I think I am going to first expose the new state and let you and I play with it, and _then_ deprecate `path`.

**Comment by paullewis** [comment]
Good plan!

**Comment by dglazkov** [comment]
Folding into #2674
