### ISSUE TITLE
You can edit code even though if you are on a read-only view

### ISSUE THREAD

**Issue by surma** [breadboard-ai/breadboard#3627]
Discovered this while using the "Invoke" node to use a subboard.

After a successful board execution, if you click the green board activity number, it looks like you are being taking to your subboard, but you are actually on a read-only view of Invoke that just happens to look like your subboard. It does say "read-only view" at the top, but it's somewhat easy to miss. So I ended up editing my "Run JavaScript" node in this view multiple times wondering why the changes are not taking effect.

In general, node attributes should probably not be editable when in a read-only view.

But it would also be nice if "Invoke" took me to the actual subboard rather than a read-only clone.

**Comment by paullewis** [comment]
Okay, one part of this I can fix, namely the read-only part. The other part I think warrants a bit more thought, because spelunking through a historic run is fun and all, but it's currently not all _that_ clear / useful. Sometimes the things you go to are within your ability to edit, like a sub board, but in other cases (components from kits) they are inherently read-only unless we were to dynamically fork them. We don't currently have a good way to distinguish those cases.
