### ISSUE TITLE
[FR] Describe input & output in a similar way to kits?

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#714]
In the editor view I use the kits and their inner `describe` functions to circumscribe the configuration for a given node. It works really well because I don't have to teach the editor much besides honoring the inputSchema with the configuration. That said, we don't currently have any kit that describes the built-in input & output nodes, and while I could hardcode that into the editor, it doesn't feel like the right call.

On a related note we somewhat bypass the Inspector API in terms of kits. Or at least we pass the kits through and also reuse them internally to the editor, whereas it might be better to provide them to the Inspector and ask for kits via the API and have it mix in the built-ins too?

**Comment by dglazkov** [comment]
As of https://github.com/breadboard-ai/breadboard/commit/56ccae50d91ca24120ccb67f4abd64a19a03cbd8, we can now inspect Kits!

Use that API instead of calling the `describe` functions directly. I even left a ~booger~ sample code to show how to use the API here:

https://github.com/breadboard-ai/breadboard/blob/56ccae50d91ca24120ccb67f4abd64a19a03cbd8/packages/breadboard-ui/src/elements/editor/editor.ts#L541-L553

Inspector API docs updated here: 
https://breadboard-ai.github.io/breadboard/docs/inspector/#kits

**Comment by dglazkov** [comment]
Declaring victory 🚢
