### ISSUE TITLE
[FR] Validate changes to the graph in Inspector

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#715]
In the current implementation I emit events that directly modify the graph descriptor that was loaded in breadboard-web. So, like, add a node here, add or remove an edge there. It's all done on trust that the edges & nodes are being created & updated correctly, and that might not hold true. It would be helpful to hand off changes to the Inspector API (including – say – configuration updates) and for it to return an updated graph.

It could also allow us to support history traversal, which is particularly valuable for the visual editor case.

From our offline chat with @aomarks it seems like could be crossover here with the TypeScript API in that both want to manipulate a graph, but for my purposes at least being able to hand off the changes .

**Comment by dglazkov** [comment]
My thinking here to add a few two-part helpers to `InspectableGraph`: one method to see if we can do it (`canDoStuff`) and another to actually do it (`doStuff`). This way, we can call the first one to make sure this will not result in an invalid graph, and call the second one to perform an action. Of course the `doStuff` will also call `canDoStuff` first, so there's no need to call `canDoStuff` if failing an action is okay.
Here are the `doStuffs` that I think we'd need:

- add edge
- remove edge
- add node
- remove node
- change node configuration
- something I am missing?

When we call these helpers on `InspectableGraph`, it will mutate the underlying graph structure accordingly, clear caches, etc.  so that next time we read it back, it's up to date.

WDYT?

**Comment by paullewis** [comment]
Sounds perfect.

**Comment by dglazkov** [comment]
As of https://github.com/breadboard-ai/breadboard/commit/ea652f3db3cf125e9bc8aa832eccb8e5f3aa46b9, there's now an Editor API: https://breadboard-ai.github.io/breadboard/docs/editor/

**Comment by dglazkov** [comment]
Declaring victory 🚢
