### ISSUE TITLE
[FR] Allow renaming of node in Editor API

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#745]
When I create a new node in the editor I give it a generic ID, like `'worker-2'`. If the user wants to change the ID I'd have to remove the old node and create a new one, which is doable, but it feels like a nicer option would be allow renaming via the Editor API. If nothing else we could have ID clashes so it'd be good to validate it. wdyt?

**Comment by dglazkov** [comment]
Sure thing. I was also thinking that maybe the id is not the best way to convey the name of the node, so I might 🧠  a bit about an actual "title" of a node and see if I can sneak it into the editor API.

**Comment by dglazkov** [comment]
See if you like the new `metadata` thing. 
<img width="568" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/1934/e263f0cb-1432-4f66-8727-e55a388bed8d">

For an example, see:
https://github.com/breadboard-ai/breadboard/blob/ee002491bb95a02f51b8799e98d59a0509aa8f76/packages/breadboard-web/src/boards/ad-writer.ts#L41-L48

There also also `canChangeMetadata` and `changeMetadata` methods on the Editor API.

So, instead of changing the id, let's just change the title. Will this work?

**Comment by paullewis** [comment]
Yes, definitely. The id is just the internal name for the node at that point, and I think it becomes more about about editing what the user sees (the meta data) 👍🏻

**Comment by dglazkov** [comment]
yay! 🚢
