### ISSUE TITLE
Schema always shows as 'connected'

### ISSUE THREAD

**Issue by paullewis** [breadboard-ai/breadboard#769]
If I head to ?mode=build&visualizer=editor I always see that the `schema` ports show as connected. When I disconnect the edge from `input` to `output`, the `text` port on `output` also shows as connected. Is that a bug in Inspector, maybe?

<img width="389" alt="nodes" src="https://github.com/breadboard-ai/breadboard/assets/617438/eb914561-0b82-4cb4-8cdb-4e78e3c261db">

**Comment by dglazkov** [comment]
The `schema` bit is working as intended: this port is technically connected, because it's value is provided via configuration. So it is `connected`, but not with a wire.  To check for that, it's `port.configured` boolean. Maybe this should be just a `PortStatus`?

The second one definitely looks like a bug. Spelunking...

**Comment by dglazkov** [comment]
Oh this one is fun. It's a race condition here:

https://github.com/breadboard-ai/breadboard/blob/ef54bc362cb0fa5dfd02b0161e050196928a752d/packages/breadboard-ui/src/elements/editor/editor.ts#L283-L306

Because the `InspectableNode.ports` is async, it drops out of the event loop and allows the next update (with the update graph) to come in, but because `this.#processing` is true, the method returns early and never updates the graph.

**Comment by paullewis** [comment]
Ahhhhhhh, okay. It was a me thing 😁 Got it.
