### ISSUE TITLE
Only remove  is reflected in ui when changing edges 

### ISSUE THREAD

**Issue by dglazkov** [breadboard-ai/breadboard#866]
While playing with the editor, found this one:

- Drop any node into the initial board
- Change the edge to point to the input of the node
- The `text` port will go red

<img width="344" alt="image" src="https://github.com/breadboard-ai/breadboard/assets/1934/74732c79-f5d2-4680-8d49-03696501ddb3">

It looks like this happens because the edge change operation consists of two steps: remove and add:

https://github.com/breadboard-ai/breadboard/blob/5bc47be55dc8eaa4b54bc43c4351660decaf1b26/packages/breadboard-ui/src/elements/editor/editor.ts#L471-L491

The `this.#expectingRefresh` flag takes care of `remove`, but not `add`. Not yet sure how to fix it, investigating...

**Comment by dglazkov** [comment]
@paullewis proposed fixed is here: https://github.com/breadboard-ai/breadboard/pull/867.
Basically, we change `LoadArgs` object identity every time we have an updated graph, and that seems to work.
However, my Lit-foo is weak and I don't know if this is slow or inefficient or what. PTAL.

**Comment by paullewis** [comment]
This is all good. Lit will only re-render when a property changes. Generally it does a strict equality check on arrays and objects, and in most cases the `loadInfo` object was the same one so it skips the re-rendering. I had been working around it with flags rather than creating new objects, though, and that was my mistake because it just generates a lot of extra cruft in the code. Which you've now removed – yay!

**Comment by paullewis** [comment]
Declaring victory on this one 🚢
